# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/trusty64'

  config.vm.hostname = "testbox"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "provision/"
    puppet.manifest_file = "init.pp"
    puppet.options = ['--parser future']
  end
  
  config.vm.provision :dashboardhosts

end
